name: Deploy Documentation

on:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/**'

jobs:
  build-publish:
    name: build-move-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build
        env:
        run: mvn clean package --projects :docs --batch-mode -Pbuild-docs
      - name: Move
        run: |
          mkdir public
          mv docs/target/public/index.html docs/index.html
      # It seems that regular users cannot use gh-pages branch, so this will just be here as an example.
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.4.1
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
